### ISSUE TITLE
Add back to top button

### ISSUE THREAD

**Issue by grimicorn** [matchboxdesigngroup/kindling-v2#17]
At some point our back to top button was stripped out below is basically the previous implementation. This can probably be improved upon but this should be a good starting point.

### HTML
```
<div title="Back to Top" class="page-top-link back-to-top" style="display: block; opacity: 1;">
	<a href="#">Return to top</a>
</div>
```
### JS
```
/**
* Initializes the back to top button.
*/
site.initBackToTop = function() {
	var pageTopLinkElem = $('.page-top-link');

	if ( pageTopLinkElem.length === 0 ) {
		return;
	} // if()

	pageTopLinkElem.click(function() {
		$(window.opera ? 'html' : 'html, body').stop(true, true).animate({ scrollTop : 0 }, 1500, 'easeInOutQuad');
		return false;
	});

	$(window).scroll(function() {
		if ($(window).scrollTop() > 150){
			pageTopLinkElem.stop(true, true).fadeIn(1000);
		} else {
			pageTopLinkElem.stop(true, true).fadeOut(1000);
		}
	});
};
```
### SCSS
```
// ==================================================
// Back to top
// ==================================================
.back-to-top {
	display: none;
	width: 40px;
	height: 40px;
	position: fixed;
	bottom: 20px;
	right: 25px;
	cursor: pointer;
	text-indent: -9999px;
	background: rgba($color2, 0.5);
	border-radius: 5px;

	a {
		display: block;
		width: 30px;
		height: 30px;
		position: absolute;
		top: 5px;
		left: 5px;
		border-radius: 999px;
		background: url("../img/page-top-link.png") center center no-repeat $theme1;
	} // a

	&:hover a { background-color: hover($theme1); }

	.backgroundsize & a {
		background: url("../img/page-top-link@2x.png") center center no-repeat $theme1;
		background-size: 30px 30px;
	} // .backgroundsize & a
} // .back-to-top
```
### Images
[images.zip](https://github.com/matchboxdesigngroup/kindling/files/761750/images.zip)

**Comment by matthewninja** [comment]
I've made an improvement to make the offset responsive. On my site, the DOM was squished on some devices, resulting in the button overlapping. So here's the code with my changes:
<code>

function() {

            var $ = jQuery, body = $('body');

            var offset = body.height()*0.4;

            var duration = 500;

            jQuery(window).scroll(function() {

                if (jQuery(this).scrollTop() > offset) {

                    jQuery('.back-to-top-btn').fadeIn(duration);

                } else {

                    jQuery('.back-to-top-btn').fadeOut(duration);

                }

            });

            jQuery('.back-to-top-btn').click(function(event) {

                event.preventDefault();

                jQuery('html, body').animate({scrollTop: 0}, duration);

                return false;

            })

        }

</code>
