### ISSUE TITLE
Fix php warning associated with 'mdg_remove_hicpo_pre_get_posts_filter' in extras.php

### ISSUE THREAD

**Issue by unscripted** [matchboxdesigngroup/kindling-v2#5]
@DHolloran This was commented out in  https://github.com/matchboxdesigngroup/kindling/commit/f51c0acb4b72fb847c6e020f603d77b264aa928d

Below is the warning it was producing:
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'mdg_remove_hicpo_pre_get_posts_filter' not found or invalid function name in /Users/cwhitmore/Dropbox/Sites/kindling.dev/wp-includes/plugin.php on line 601`

**Comment by grimicorn** [comment]
This should not be an issue anymore
